version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.2.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xcodebuild -project Demo.xcodeproj -scheme "iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X' build | xcpretty
      - run: xcodebuild -project Demo.xcodeproj -scheme "tvOS" -destination 'platform=tvOS Simulator,name=Apple TV,OS=12.2' build | xcpretty

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
